### ISSUE TITLE
weightedRandom: Reduce without creating new arrays

### ISSUE THREAD

**Issue by tmedwards** [AlyxMS/Twine-SugarCube-repository#1]
https://github.com/AlyxMS/Twine-SugarCube-repository/blob/5570cafda7770b2a31d0091e664737086b11ac37/function_weightedRandom.js#L2

You don't need to create a new array for every iteration of the reducer callback.  Specify an initial value of `0` for the accumulator and just add the weight of the current value.  E.g.,
```js
	let randomNumber = weightedArray.reduce((a, c) => a + c[1], 0) * Math.random();
```

**Comment by AlyxMS** [comment]
Yup that's muuuuuch better. Somehow using an initial value completely slipped my mind.

The first version was (a, b) => a[1] + b[1], when that didn't work, I *fixed* it like that and thought I was being clever
